export const localState = $state({
  appContainer: undefined as any,
  navigationToken: 0,
  previewPaneToken: 0,
  currentQuickLookPath: null as any,
  currentArchivePath: null as any,
  currentProgressOperationId: null as any,
  remoteProviderActions: null as any,
  ftpRemoteActions: null as any,
  webdavRemoteActions: null as any,
  networkMountActions: null as any,
  remoteControllerReady: false,
  activeRemotePanel: 'welcome',
  remoteTransferHost: null as any,
  watchedDirectoryPath: null as any,
  fileChangeRefreshTimer: null as any,
  s3Auth: null as any,
  s3FolderStack: [] as any[],
  s3SelectedEntry: null as any,
  s3Entries: [] as any[],
  remoteTransfers: [] as any[],
  undoStack: [] as any[],
  redoStack: [] as any[],
  isSettingColorLabel: false,
  MAX_UNDO_STACK: 50,
  advancedRenameTargets: [] as any[],
  advancedRenamePlans: [] as any[]
});
